### ISSUE TITLE
RKNN的那个有点问题 #BUG

### ISSUE THREAD

**Issue by erquren** [cqu20160901/yolov8n_official_onnx_tensorRT_rknn_horizon#1]
单目标的最大得分也就0.6 不知道是模型问题还是后处理问题

**Comment by cqu20160901** [comment]
这个模型训练使用的数据非常少，只是用来测试流程，pytorch效果也都不好。

**Comment by erquren** [comment]
> 这个模型训练使用的数据非常少，只是用来测试流程，pytorch效果也都不好。
在你的另一个仓库https://github.com/cqu20160901/yolov8_rknn_Cplusplus.git
这里面的模型输出和当前仓库的不一致，yolov8_rknn_Cplusplus.git 里的模型精度是准确的，那个是80类激活函数也是relu的，不过那个模型的输出有6个，那个转换的步骤和这个有什么区别吗？
